format = "$username$hostname$directory"
right_format = '$cmd_duration$git_status'

add_newline = false

[username]
format = '[\[](bold red)[$user]($style)[@](green)'
show_always = true

[hostname]
ssh_only = false
ssh_symbol = 'üåê '
trim_at = '.'
format = '[$ssh_symbol$hostname ]($style)'
style = 'bold blue'
disabled = false

[directory]
truncation_length = 1
truncate_to_repo = false 
style = '#cba6f7'
fish_style_pwd_dir_length = 1
format = '[$path]($style)[$read_only]($read_only_style)[\]](bold red)\$ '

[cmd_duration]
format = '([\[$duration\]]($style))'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'
